name: Rails
on: push

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: bin/rails db:create db:migrate
      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test
